package edu.proyectofinal.gui;

import edu.proyectofinal.process.UserManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

public class AddUser extends javax.swing.JFrame {

    private DefaultTableModel tablUsers;
    private UserManager userManager;

    /**
     * Creates new form AddUser
     */
    public AddUser(DefaultTableModel tablUsers, UserManager userManager) {
        initComponents();
        this.tablUsers = tablUsers;
        setLocationRelativeTo(null);
        this.userManager = userManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        fieldAge = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cBVip = new javax.swing.JCheckBox();


        ((AbstractDocument) fieldAge.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {

                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (text.matches("\\d*")) { // Solo acepta dígitos
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese el nombre del usuario");

        jLabel2.setText("Ingrese la edad del usuario");

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirmar");
        btnConfirm.setActionCommand("confirmar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setActionCommand("confirmar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        cBVip.setText("Vip");
        cBVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBVipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(84, 84, 84)
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 21, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(cBVip)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnCancelar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnConfirm))
                                        .addComponent(fieldAge)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnConfirm)
                                        .addComponent(btnCancelar)
                                        .addComponent(cBVip))
                                .addContainerGap())
        );

        pack();
    }

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {
        if (fieldName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(AddUser.this, "No puede dejar el nombre vacio");
        }
        else if (fieldAge.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(AddUser.this, "No puede dejar la edad vacia");
        }
        else {
            try {
                int edad = Integer.parseInt(fieldAge.getText().trim());

                if (edad < 6|| edad > 140) {
                    JOptionPane.showMessageDialog(AddUser.this, "Edad invalida (6-140 años)");
                }
                else {
                    if(cBVip.isSelected()){
                        if(edad < 18){
                            JOptionPane.showMessageDialog(AddUser.this, "No se puede registrar un usuario VIP menor de edad");
                            return;
                        }
                        userManager.addUser(fieldName.getName(),edad,"VIP");
                        tablUsers.addRow(new Object[]{userManager.getUsers().size(),fieldName.getText(),edad,0,"VIP"});
                        JOptionPane.showMessageDialog(AddUser.this, "Usuario registrado con exito");
                        this.dispose();
                    }else {
                        userManager.addUser(fieldName.getText(), edad, null);
                        tablUsers.addRow(new Object[]{tablUsers.getRowCount() + 1,fieldName.getText(), edad, 0, userManager.findUserByName(fieldName.getText()).getUserType()});


                        JOptionPane.showMessageDialog(AddUser.this, "Usuario registrado con exito");
                        this.dispose();
                    }
                }
            }
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(AddUser.this, "La edad debe ser un numero valido");
            }
        }

    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void cBVipActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JCheckBox cBVip;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration
}