package edu.proyectofinal.gui;


import edu.proyectofinal.data.Book;
import edu.proyectofinal.data.User;
import edu.proyectofinal.process.BookManager;
import edu.proyectofinal.process.LoanManager;
import edu.proyectofinal.process.UserManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * @author Mike
 */
public class MakeLoan extends javax.swing.JFrame {

    private DefaultTableModel tablBooks;
    private DefaultTableModel tablLoans;
    private DefaultTableModel tablUsers;
    private LoanManager loanManager;
    private UserManager userManager;
    private BookManager bookManager;

    /**
     * Creates new form MakeLoan
     */
    public MakeLoan(DefaultTableModel tablLoans, LoanManager loanManager, UserManager userManager, BookManager bookManager, DefaultTableModel tablBooks, DefaultTableModel tablUsers) {
        initComponents();
        this.tablLoans = tablLoans;
        this.loanManager = loanManager;
        this.userManager = userManager;
        this.bookManager = bookManager;
        this.tablBooks = tablBooks;
        this.tablUsers = tablUsers;
        setCombUsers(userManager);
        setjCombBooks(bookManager);
    }

    public void setCombUsers(UserManager userManager){
        jCombUsers.addItem("Seleccione un usuario");
        for (User user: userManager.getUsers()){
            if (user.getUserType() != "Jr" && user.getActiveLend() < user.getMaxLoans()){
                jCombUsers.addItem(user.getName() + " - " + user.getId());
            }

        }

    }

    public void setjCombBooks(BookManager bookManager) {
        jCombBooks.addItem("Seleccione un libro");
        for (int i = 0; i < tablBooks.getRowCount(); i++) {
            int availableCopies = (int) tablBooks.getValueAt(i, 4);
            if (availableCopies > 0) {
                String title = (String) tablBooks.getValueAt(i, 0);
                String author = (String) tablBooks.getValueAt(i, 1);
                jCombBooks.addItem(title + " - " + author + " - " + availableCopies);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jCombUsers = new javax.swing.JComboBox<>();
        jCombBooks = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCombUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jCombBooks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel1.setText("Eliga el usuario");

        jLabel2.setText("Eliga el libro");

        btnConfirm.setText("Confirmar");
        btnConfirm.setActionCommand("confirmar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.setActionCommand("confirmar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCombUsers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jCombBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(130, 130, 130))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConfirm)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCombBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCombUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnConfirm)
                                        .addComponent(btnCancel))
                                .addContainerGap())
        );

        pack();
    }

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {
        String selectedUser = (String) jCombUsers.getSelectedItem();
        String selectedBook = (String) jCombBooks.getSelectedItem();

        if (selectedUser != null && selectedUser.equals("Seleccione un usuario")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario válido.");
        } else if (selectedBook != null && selectedBook.equals("Seleccione un libro")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un libro válido.");
        } else {
            String[] userParts = selectedUser.split(" - ");
            String userName = userParts[0];
            int userId = Integer.valueOf(userParts[1]);
            String[] bookParts = selectedBook.split(" - ");
            String bookTitle = bookParts[0];

            LocalDateTime today = LocalDateTime.now();
            System.out.println(userManager.findUserById(userId).getUserType());
            LocalDateTime endDate = today.plusDays(userManager.findUserById(userId).getLoanDurationDays());
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String stringToday = today.format(formatter);
            String stringEndDate = endDate.format(formatter);

            loanManager.addLoan(bookManager.findBookByTitle(bookTitle), userManager.findUserByName(userName), stringToday, loanManager.calculateStatus(stringToday, stringEndDate));
            tablLoans.addRow(new Object[]{ userName, bookTitle, stringToday, stringEndDate , loanManager.calculateDaysBetween(stringToday, stringEndDate), loanManager.calculateStatus(stringToday, stringEndDate)});

            for (int i = 0; i < tablBooks.getRowCount(); i++) {
                if (tablBooks.getValueAt(i, 0).equals(bookTitle)) {
                    int availableCopies = (int) tablBooks.getValueAt(i, 4) - 1;
                    tablBooks.setValueAt(availableCopies, i, 4);
                    break;
                }
            }

            for (int i = 0; i < tablUsers.getRowCount(); i++) {
                if (tablUsers.getValueAt(i, 1).equals(userName)) {
                    int activeLoans = (int) tablUsers.getValueAt(i, 3) + 1;
                    tablUsers.setValueAt(activeLoans, i, 3);
                    break;
                }
            }

            this.dispose();
        }
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();

    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> jCombBooks;
    private javax.swing.JComboBox<String> jCombUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration
}
